version: '3.1'

services:
  check_cluster:
    build:
      context: .
      dockerfile: Dockerfile

    image: cluster_check:stable

    restart: always
    volumes:
      - /root/ccp/check:/Project/demo